application: quicktouchmath
version: 1
runtime: python
api_version: 1

handlers:

- url: /web
  static_dir: web

- url: /game
  static_dir: game

- url: /scripts
  static_dir: scripts
  
- url: /style
  static_dir: style
  
- url: /images
  static_dir: images
  
- url: /questions
  static_dir: questions

- url: .*
  script: main.py